- name: Instalar apache y git
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - git

- name: Descarga de pagina web
  git:
    repo: https://github.com/msaunevale/proyecto-paracas-2013.git
    dest: /var/www/html
    version: "master"

- name: Copiar de archivo httpd.conf
  template:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify: reinicio_apache

- name: Inicio y persintencia del servicio de Apache
  systemd:
    name: httpd
    state: started
    enabled: yes
